<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickMail</name>
   <tag></tag>
   <elementGuidId>10220aec-ca68-4c0d-8f92-9ab3266072c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='https://webr12accounts.wizards.com/NewAccount/RedirectToVerification/629044d9-5442-4c10-b7aa-ed90827c1d0c']</value>
   </webElementProperties>
</WebElementEntity>
